### ISSUE TITLE
training set

### ISSUE THREAD

**Issue by liukaishu** [FahrulRozzy/YOLOv8n-methane-gas-leak-detection#1]
Hello, I would like to ask, do you have a dataset for the training of this project, I can't find the relevant dataset on the Internet, I hope you can provide a copy. I hope you can provide a copy.

**Comment by FahrulRozzy** [comment]
You can download it from the following link
https://drive.google.com/drive/folders/1JKEMtCGPSq2IqGk4uXZP9A6gr8fyJsGC?usp=sharing

Sources of the following research:
https://doi.org/10.1016/j.apenergy.2019.113998
https://doi.org/10.1016/j.energy.2021.121516
